[package]
name = "tastyworks"
version = "0.1.0"
description = "Unofficial Tastyworks API"
authors = ["Tobias Mansfield-Williams <contact@tmwhere.com>"]
repository = "https://github.com/thetatool/tastyworks-rs"
license = "MIT"
edition = "2018"

[dependencies]
chrono = "0.4.13"
csv = "1.1.3"
dirs = "3.0.1"
futures = "0.3.5"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
num-rational = "0.3.0"
num-traits = { version = "0.2.1", default-features = false }
ordered-float = "2.0.0"
regex = "1.3.9"
reqwest = { version = "0.10.6", features = ["json"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
tungstenite = "0.11.0"
url = "2.1.0"
